### PR TITLE
Update to 0.2.7.1

### PR DESCRIPTION
**Pull request by tupui**
Required by pathos 0.2.1

### CODE REVIEW

**Comment by tupui** [comment]
@DanCodigaMWRA @ocefpaf I re rendered the feedstock and updated recipe to use latest version from PyPi. Also, this re-render the feedstock.

**Comment by ocefpaf** [comment]
Thanks @tupui! Consider adding yourself as a maintainer for this feedstock :wink:

**Comment by ghost** [comment]
@tupui adding yourself as maintainer would indeed be very helpful

**Comment by tupui** [comment]
@DanCodigaMWRA @ocefpaf Thank you both for integrating this and proposing to be a maintainer! I will create a PR for this then.

**Pull request merged**
