### PR TITLE
Switch 0.3.1.1 to noarch: python

### LINKED ISSUE #28: build request: noarch v0.3.1.1
## Issue
The `conda-forge/osx-arm64::apache-beam` builds are unsolvable due to lack of compatible `dill >=0.3.1.1,<0.3.2.0` builds. Further details at conda-forge/apache-beam-feedstock#44.

## Recommendation
Maintainers should attempt issuing a `noarch` build for v0.3.1.1 via a new branch in the repository. This would keep default branch clean while still resolving the issue. This is a one-off request - branch would not need any further maintenance.

See [documentation on using branches to issue alternate versions](https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions).

### PR DESCRIPTION
**Pull request by xylar**
This should be okay because we can remove the optional Windows
dependency.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

closes #28

### CODE REVIEW

**Comment by xylar** [comment]
@ocefpaf, I don't seem to be able to make a branch on this feedstock.  I'm sorry to bother you about this.  I figured I'd be able to take care of it.  If you don't mind, could you make a branch called `0.3.1.x` that points to the following hash?
https://github.com/conda-forge/dill-feedstock/tree/910ed14bfed79bd50d6fc1cfc20cc47a68761eb1
I believe that's the last commit before the update to 0.3.2.

Sorry for the hassle.  I'm not sure why I can't push a branch.

**Comment by ocefpaf** [comment]
> @ocefpaf, I don't seem to be able to make a branch on this feedstock. I'm sorry to bother you about this. I figured I'd be able to take care of it. If you don't mind, could you make a branch called `0.3.1.x` that points to the following hash? https://github.com/conda-forge/dill-feedstock/tree/910ed14bfed79bd50d6fc1cfc20cc47a68761eb1 I believe that's the last commit before the update to 0.3.2.

Done: https://github.com/conda-forge/dill-feedstock/tree/0.3.1.x
 
> Sorry for the hassle. I'm not sure why I can't push a branch.

No biggie. Thanks for taking care of this!

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@ocefpaf, thanks so much!  I really appreciate it.

**Comment by xylar** [comment]
I don't think I actually got registered as a maintainer for some reason.  I can't merge this either.  @ocefpaf, would you do that for me as well :-(

**Comment by xylar** [comment]
Thanks again!

**Pull request merged**
